# Generated by Django 4.2 on 2025-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lloguer', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_inici',
            field=models.DateField(),
        ),
    ]
