# Generated by Django 4.2 on 2025-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lloguer', '0003_alter_reserva_data_inici'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
